config/routes.rb
S0::Application.routes.draw do

  resources :searches, path: "/search"

  concern :reviewable do 
    resources :reviews, only: [:create, :destroy, :update]
  end

  get "/movies/:id/reviews", to:"movies#show_reviews"
  get "/movies/:id/posts", to:"movies#show_posts"
  get "/series/:id/reviews", to:"serials#show_reviews"
  get "/series/:id/posts", to:"serials#show_posts"
  get "/series/:serial_id/seasons/:id/reviews", to: "seasons#show_reviews"
  get "/series/:serial_id/seasons/:id/posts", to: "seasons#show_posts"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/reviews", to:"episodes#show_reviews"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/posts", to:"episodes#show_posts"

  concern :commentable do 
    resources :posts, only: [:index, :create, :destroy, :update]
  end

  resources :movies, concerns: [:reviewable, :commentable]

  resources :serials, path: "/series", concerns: [:reviewable, :commentable] do
    resources :seasons, concerns: [:reviewable, :commentable] do
        resources :episodes, concerns: [:reviewable, :commentable]
    end
  end
  
  resources :sessions, only: [:create, :new, :destroy]
  get "/login", to: "sessions#create", as: :log_in
  get "/logout", to: "sessions#destroy", as: :log_out
  get "/signup", to: "users#new", as: :sign_up
  match "/login", to: "sessions#create", via: :post

  get "403", to: "pages#no_access", as: :access_denied

  get "/me", to: "users#me", as: :my_profile
  get "/me/shows", to:"followed_shows#shows", as: :my_shows
  get "/me/series", to:"followed_shows#serials", as: :my_serials
  get "/me/movies", to:"followed_shows#movies", as: :my_movies
  get "/me/watchlist", to:"watchlists#my_watchlist", as: :my_watchlist
  get "/me/tracking/serials/:id", to:"watched#tracking", as: :my_tracking
  get "/me/tracking/serials/:serial_id/seasons/:season_id", to:"watched#detail", as: :my_tracking_detail
  get "/me/seen", to:"watched#my_watched", as: :my_watched

  resources :users do
    resource :watchlists, path: "/watchlist"
  end
  resources :users do
    resource :watcheds, path: "/watched"
  end

  get "/series/:id/add", to:"serials#add", as: :add_serial
  get "/series/:id/remove", to:"serials#remove", as: :remove_serial
  get "/movies/:id/add", to:"movies#add", as: :add_movie
  get "/movies/:id/remove", to:"movies#remove", as: :remove_movie
  get "/series/:id/watch", to:"serials#watch", as: :watch_serial
  get "/series/:id/unwatch", to:"serials#unwatch", as: :unwatch_serial
  get "/series/:id/seen", to:"serials#seen", as: :seen_serial
  get "/series/:id/unseen", to:"serials#unseen", as: :unseen_serial
  get "/movies/:id/watch", to:"movies#watch", as: :watch_movie
  get "/movies/:id/unwatch", to:"movies#unwatch", as: :unwatch_movie
  get "/watchlist/:id/remove", to:"watchlist#remove", as: :remove_from_watchlist
  get "/movies/:id/seen", to:"movies#seen", as: :seen_movie
  get "/movies/:id/unseen", to:"movies#unseen", as: :unseen_movie
  get "/series/:serial_id/seasons/:id/seen", to:"seasons#seen", as: :seen_season
  get "/series/:serial_id/seasons/:id/unseen", to:"seasons#unseen", as: :unseen_season
  get "/series/:serial_id/seasons/:season_id/episodes/:id/seen", to:"episodes#seen", as: :seen_episode
  get "/series/:serial_id/seasons/:season_id/episodes/:id/unseen", to:"episodes#unseen", as: :unseen_episode

  get "/me/:id/watching", to:"watched#my_watched", as: :my_watching_series
  get "/me/:id/seen/series", to:"watched#series", as: :my_seen_series
  get "/me/:id/seen/movies", to:"watched#movies", as: :my_seen_movies

  match "/series/:serial_id/seasons/:season_id/episodes/:id/add_user_tags", to: "episodes#add_user_tags", via: :post
  get "/series/:serial_id/seasons/:season_id/episodes/:id/remove_user_tag/:tag_id", to: "episodes#remove_user_tag"

  root 'pages#index'

  namespace :api, defaults: {format: 'json'} do
    
    resources :movies do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'seen'
        get 'unseen'
        get 'reviews'
        get 'posts'
      end
    end

    resources :serials, path: "series" do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'reviews'
        get 'posts'
      end

      resources :seasons do
        member do
          get 'reviews'
          get 'posts'
        end

        resources :episodes do
          member do
            get 'seen'
            get 'unseen'
            get 'reviews'
            get 'posts'
          end
        end
      end
    end
  end

  

end

app/models/season.rb
class Season < ActiveRecord::Base
  include UserContentable
  
  belongs_to :serial
  has_many :episodes, dependent: :destroy

  validates :number, uniqueness: {scope: :serial_id}, presence: true

	def to_param
	    number
	end

    def self.find(input)
    	find_by(number: input)
    end
end

app/controllers/api/seasons_controller.rb
module Api
  class SeasonsController < ApiApplicationController

    before_filter :token_admin, only: [:create, :update, :destroy]
    #before_filter :token_user, only: [:add, :remove, :watch, :unwatch, :seen, :unseen]
    
    before_action :set_serial
    before_action :set_season, except: [:index, :create ]
    before_action :set_reviews, only:[:show, :reviews]
    before_action :set_posts, only:[:show, :posts]

    # GET /seasons
    # GET /seasons.json
    def index
      render json: {seasons: @serial.seasons, series: @serial}
    end

    # GET /seasons/1
    # GET /seasons/1.json
    def show
      render json: {season: @season, series: @serial}
    end

    # POST /seasons
    # POST /seasons.json
    def create
      @serial = Serial.find(params[:serial_id])
      @season = Season.create(season_params)
      @season.serial_id = @serial.id
      @serial.seasons << @season
      if @season.id
        render json: {success: "true", message: "Season has been created", season: @season, series: @serial}
      else
        render json: {success: "false", message: "Season was not created"}
      end
    end

    # PATCH/PUT /seasons/1
    # PATCH/PUT /seasons/1.json
    def update
      respond_with @season.update(season_params)
    end

    # DELETE /seasons/1
    # DELETE /seasons/1.json
    def destroy
      if @season
        @season.destroy
        render json: {success: "true", message:"Season was successfully deleted", series: @serial}
      else
        render json: {success: "false", message:"Season doesn't exists", series: @serial}
      end
    end

    def reviews
      respond_with @season.reviews
    end

    def posts
      respond_with @season.posts
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_season
        @season = @serial.seasons.find_by(number: params[:id])
      end

      def set_serial
        @serial = Serial.find(params[:serial_id])
      end

      def set_reviews
        @reviews = @season.reviews
      end
      
      def set_posts
        @posts = @season.posts
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def season_params
        params.require(:season).permit(:description, :date, :number, :serial_id)
      end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  include UserReviewsPosts

  skip_before_filter :user_admin, only: [:show, :index, :show_reviews, :show_posts, :seen, :unseen]
  skip_before_filter :authorize, only: [:show, :index, :show_reviews, :show_posts]
  before_action :set_serial
  before_action :set_season, except: [:index, :create, :new]
  before_action :set_reviews, only: [:show, :show_reviews]
  before_action :set_posts, only: [:show, :show_posts]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = @serial.seasons
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @serial = Serial.find(params[:serial_id])
    @season = Season.new(season_params)
    @season.serial_id = @serial.id

    respond_to do |format|
      if @season.save
        format.html { redirect_to [@serial,@season], notice: 'Season was successfully created.' }
        format.json { render action: 'show', status: :created, location: @season }
      else
        format.html { render action: 'new' }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to [@serial,@season], notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to serial_seasons_url }
      format.json { head :no_content }
    end
  end

  def seen
    if current_user
      @season.episodes.each do |episode|
        unless current_user.watched.episodes.include?(episode)
          current_user.watched.episodes << episode
          current_user.score_update(nil)
        end
      end 
      respond_to do |format|
          format.html { redirect_to serial_season_url(@serial,@season), notice: "This whole season was marked as seen!" }
          format.js { render 'layouts/update_action_menu' }
      end
    end
  end

  def unseen
    if current_user
      @season.episodes.each do |episode|
        if current_user.watched.episodes.include?(episode)
          current_user.watched.episodes.delete(episode)
          current_user.score_update(nil)
        end
      end 
      respond_to do |format|
          format.html { redirect_to serial_season_url(@serial,@season), notice: "This whole season was marked as unseen!" }
          format.js { render 'layouts/update_action_menu' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = @serial.seasons.find_by(number: params[:id])
    end

    def set_serial
      @serial = Serial.find(params[:serial_id])
    end

    def set_reviews
      @reviews = @season.reviews
    end
    
    def set_posts
      @posts = @season.posts
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:description, :date, :number, :serial_id)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_action_menu.html.erb
<ul>
  <li><%= seen_unseen_season_link(@season) %></li>
</ul>

app/views/seasons/_admin_bar.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
    <li><%= link_to 'Edit Season', edit_serial_season_path(@serial,@season) %></li>
    <li><%= link_to 'New Episode', new_serial_season_episode_path(@serial,@season) %></li>
  </ul>
<% end %>

app/views/seasons/_content.html.erb
<div class="show-header">
<div class="show-header-title">
  <p class="bread-crumb"><%= link_to @serial.name, serial_path(@serial) %></p>
  <h1>Season <%= @season.number.to_s %></h1>
  <%= link_to "View all seasons", serial_seasons_path(@serial), class: "all-seasons-link" %>
</div>

<p class="description"><%= simple_format @season.description %></p>
</div>

app/views/seasons/_form.html.erb
<%= form_for([@serial,@season]) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date,start_year: 1900, end_year: Time.now.year+2, discard_hour: true %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/_sidebar.html.erb
  <div class="show-action-menu">
    <%= render 'action_menu' %>
  </div>

  <img src="<%= @serial.poster%>">

  <div class="show-detail-module show-details">
    <h3>Season Details</h3>
    <ul>
      <li>Date: <%= @season.date.to_date().to_s(:long) %></li>
    </ul>
  </div>

  <div class="show-detail-module episodes-list">
    <h3><%= link_to "Episodes »", serial_season_episodes_path(@serial,@season) %></h3>
    <% if @season.episodes.empty? %>
    <p>We're sorry, we don't have any episodes yet</p>
    <% else %>
      <ul>
        <% @season.episodes.sort_by{|e| e.number}.each do |e| %>
        <li><%= link_to "Episode #{e.number}", serial_season_episode_path(@serial,@season,e) %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', serial_season_path(@serial,@season) %> |
<%= link_to 'Back', serial_seasons_path(@serial) %>

app/views/seasons/index.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
    <li><%= link_to 'New Season', new_serial_season_path(@serial) %></li>
  </ul>
<% end %>

<div class="show-sidebar">
  <div class="show-action-menu">
  </div>

  <img src="<%= @serial.poster%>">

  <div class="show-detail-module show-details">
    <h3>Serial Details</h3>
    <ul>
      <li>Date: <%= @serial.date.to_date().to_s(:long) %></li>
      <li>Genre: <%= @serial.genre %></li>
    </ul>
  </div>


</div>

<div class="show-content">
  <div class="show-header">
    <div class="show-header-title">
      <h1><%= link_to @serial.name, serial_path(@serial) %></h1>
    </div>

    <p class="description"><%= @serial.description %></p>
  </div>

  <div class="show-list show-season-list">
    <h2>Seasons</h2>

    <% if @serial.seasons.empty? %>
      <p class="center-warning">Oops, we didn't find any seasons!</p>
    <% else %>
      <% @serial.seasons.sort_by{|s| s.number}.each do |season| %>
        <div class="show-season-list-item">
          <div class="number"><%= link_to season.number, serial_season_path(@serial,season) %></div>
          <p class="description"><%= season.description %></p>
          <div class="episodes-number">
            
            <p><%= season.episodes.size %></p>
            <small>Episodes</small>
          </div>
          <!--<div class="item-action">
            
          </div> -->
        </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', serial_seasons_path(@serial) %>

app/views/seasons/show.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
    <li><%= link_to 'Edit Season', edit_serial_season_path(@serial,@season) %></li>
    <li><%= link_to 'New Episode', new_serial_season_episode_path(@serial,@season) %></li>
  </ul>
<% end %>

<div class="show-sidebar">
  <div class="show-action-menu">
  </div>

  <img src="http://placehold.it/216x319&text=<%= @serial.name+ ' Season '+@season.number.to_s %>">

  <div class="show-detail-module show-details">
    <h3>Season Details</h3>
    <ul>
      <li>Date: <%= @season.date.to_date().to_s(:long) %></li>
    </ul>
  </div>

  <div class="show-detail-module episodes-list">
      <h3><%= link_to "Episodes »", serial_season_episodes_path(@serial,@season) %></h3>
    <% if @season.episodes.empty? %>
    <p>We're sorry, we don't have any episodes yet</p>
    <% else %>
      <ul>
        <% @season.episodes.each do |e| %>
        <li><%= link_to "Episode #{e.number}", serial_season_episode_path(@serial,@season,e) %></li>
        <% end %>
      </ul>
    <% end %>
  </div>


</div>

<div class="show-content">
  <div class="show-header">
    <div class="show-header-title">
      <p class="bread-crumb"><%= link_to @serial.name, serial_path(@serial) %></p>
      <h1>Season <%= @season.number.to_s %></h1>
      <%= link_to "View all seasons", serial_seasons_path(@serial), class: "all-seasons-link" %>
    </div>

    <p class="description"><%= @season.description %></p>
  </div>

  <div class="show-users-content">
    <%= render "layouts/user_content" %>
  </div>
</div>

app/views/seasons/show_posts.html.erb
<%= render 'admin_bar' %>

<div class="show-sidebar">
  <%= render 'sidebar' %>
</div>

<div class="show-content"> 
  <%= render 'content' %>

  <div class="show-users-content">
    <%= render "layouts/user_content_posts" %>
  </div>
</div>

app/views/seasons/show_reviews.html.erb
<%= render 'admin_bar' %>

<div class="show-sidebar">
  <%= render 'sidebar' %>
</div>

<div class="show-content"> 
  <%= render 'content' %>

  <div class="show-users-content">
    <%= render "layouts/user_content_reviews" %>
  </div>
</div>