config/routes.rb
S0::Application.routes.draw do

  resources :searches, path: "/search"

  concern :reviewable do 
    resources :reviews, only: [:create, :destroy, :update]
  end

  get "/movies/:id/reviews", to:"movies#show_reviews"
  get "/movies/:id/posts", to:"movies#show_posts"
  get "/series/:id/reviews", to:"serials#show_reviews"
  get "/series/:id/posts", to:"serials#show_posts"
  get "/series/:serial_id/seasons/:id/reviews", to: "seasons#show_reviews"
  get "/series/:serial_id/seasons/:id/posts", to: "seasons#show_posts"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/reviews", to:"episodes#show_reviews"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/posts", to:"episodes#show_posts"

  concern :commentable do 
    resources :posts, only: [:index, :create, :destroy, :update]
  end

  resources :movies, concerns: [:reviewable, :commentable]

  resources :serials, path: "/series", concerns: [:reviewable, :commentable] do
    resources :seasons, concerns: [:reviewable, :commentable] do
        resources :episodes, concerns: [:reviewable, :commentable]
    end
  end
  
  resources :sessions, only: [:create, :new, :destroy]
  get "/login", to: "sessions#create", as: :log_in
  get "/logout", to: "sessions#destroy", as: :log_out
  get "/signup", to: "users#new", as: :sign_up
  match "/login", to: "sessions#create", via: :post

  get "403", to: "pages#no_access", as: :access_denied

  get "/me", to: "users#me", as: :my_profile
  get "/me/shows", to:"followed_shows#shows", as: :my_shows
  get "/me/series", to:"followed_shows#serials", as: :my_serials
  get "/me/movies", to:"followed_shows#movies", as: :my_movies
  get "/me/watchlist", to:"watchlists#my_watchlist", as: :my_watchlist
  get "/me/tracking/serials/:id", to:"watched#tracking", as: :my_tracking
  get "/me/tracking/serials/:serial_id/seasons/:season_id", to:"watched#detail", as: :my_tracking_detail
  get "/me/seen", to:"watched#my_watched", as: :my_watched

  resources :users do
    resource :watchlists, path: "/watchlist"
  end
  resources :users do
    resource :watcheds, path: "/watched"
  end

  get "/series/:id/add", to:"serials#add", as: :add_serial
  get "/series/:id/remove", to:"serials#remove", as: :remove_serial
  get "/movies/:id/add", to:"movies#add", as: :add_movie
  get "/movies/:id/remove", to:"movies#remove", as: :remove_movie
  get "/series/:id/watch", to:"serials#watch", as: :watch_serial
  get "/series/:id/unwatch", to:"serials#unwatch", as: :unwatch_serial
  get "/series/:id/seen", to:"serials#seen", as: :seen_serial
  get "/series/:id/unseen", to:"serials#unseen", as: :unseen_serial
  get "/movies/:id/watch", to:"movies#watch", as: :watch_movie
  get "/movies/:id/unwatch", to:"movies#unwatch", as: :unwatch_movie
  get "/watchlist/:id/remove", to:"watchlist#remove", as: :remove_from_watchlist
  get "/movies/:id/seen", to:"movies#seen", as: :seen_movie
  get "/movies/:id/unseen", to:"movies#unseen", as: :unseen_movie
  get "/series/:serial_id/seasons/:id/seen", to:"seasons#seen", as: :seen_season
  get "/series/:serial_id/seasons/:id/unseen", to:"seasons#unseen", as: :unseen_season
  get "/series/:serial_id/seasons/:season_id/episodes/:id/seen", to:"episodes#seen", as: :seen_episode
  get "/series/:serial_id/seasons/:season_id/episodes/:id/unseen", to:"episodes#unseen", as: :unseen_episode

  get "/me/:id/watching", to:"watched#my_watched", as: :my_watching_series
  get "/me/:id/seen/series", to:"watched#series", as: :my_seen_series
  get "/me/:id/seen/movies", to:"watched#movies", as: :my_seen_movies

  match "/series/:serial_id/seasons/:season_id/episodes/:id/add_user_tags", to: "episodes#add_user_tags", via: :post
  get "/series/:serial_id/seasons/:season_id/episodes/:id/remove_user_tag/:tag_id", to: "episodes#remove_user_tag"

  root 'pages#index'

  namespace :api, defaults: {format: 'json'} do
    
    resources :movies do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'seen'
        get 'unseen'
        get 'reviews'
        get 'posts'
      end
    end

    resources :serials, path: "series" do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'reviews'
        get 'posts'
      end

      resources :seasons do
        member do
          get 'reviews'
          get 'posts'
        end

        resources :episodes do
          member do
            get 'seen'
            get 'unseen'
            get 'reviews'
            get 'posts'
          end
        end
      end
    end
  end

  

end

app/models/serial.rb
class Serial < Show
	include UserContentable
	
	has_many :seasons, dependent: :destroy

	def to_param
        [id,name.parameterize].join("-")
    end

    def self.find(input)
    	find_by(id: input.split("-")[0])
    end

	def self.search_poster(title)
		  	apikey = APP_CONFIG['token_t'];
		  	baseUrl = "http://api.trakt.tv/search";

		  	moviesSearchUrl = baseUrl + '/shows.json/' + apikey;

			query = URI.encode(title)
			url = moviesSearchUrl + '?query=' + query
			uri = URI.parse(url)

			http = Net::HTTP.new(uri.host, uri.port)
			http.use_ssl = false
			http.verify_mode = OpenSSL::SSL::VERIFY_NONE
			request = Net::HTTP::Get.new(uri.request_uri)
			status = JSON.parse(http.request(request).body)
	end


end

app/controllers/api/serials_controller.rb
module Api
  class SerialsController < ApiApplicationController

    before_filter :token_admin, only: [:create, :update, :destroy]
    before_filter :token_user, only: [:add, :remove, :watch, :unwatch, :seen, :unseen]

    before_action :set_serial, except: [:index, :create, :new]
    before_action :set_reviews, only: [:show, :reviews]
    before_action :set_posts, only:[:show, :posts]


    # GET /serials
    # GET /serials.json
    def index
      respond_with Serial.all
    end

    # GET /serials/1
    # GET /serials/1.json
    def show
      respond_with @serial
    end

    # POST /serials
    # POST /serials.json
    def create
      @serial = Serial.new(serial_params)
      render json: {success: "true", message: "Series has been created", series: @serial}
    end

    # PATCH/PUT /serials/1
    # PATCH/PUT /serials/1.json
    def update
      @serial.update(serial_params)
      render json: {success: "true", message: "Series has been updated", series: @serial}
    end

    # DELETE /serials/1
    # DELETE /serials/1.json
    def destroy
      if @serial
        @serial.destroy
        render json: {success: "true", message: "Series has been destroyed"}
      else
        render json: {success: "false", message: "Series doesn't exist"}
      end
    end

    def add
      if token_user
        if token_user.serials.include?(@serial)
          render json: {success: "false", message: "User already has series.", series: @serial}
        else
          token_user.serials << @serial
          render json: {success: "true", message: "User has added series.", series: @serial}
        end
      end
    end

    def remove
      if token_user
        if token_user.serials.include?(@serial)
          token_user.serials.delete(@serial)
          render json: {success: "true", message: "User has removed this series.", series: @serial}
        else
          render json: {success: "false", message: "User doesn't have added this series", series: @serial}
        end
      end
    end

    def watch
      if token_user
        if token_user.watchlist.serials.include?(@serial)
          render json: {success: "false", message: "User already has series in watchlist", series: @serial}
        else
          token_user.watchlist.serials << @serial
          render json: {success: "true", message: "User has added series to watchlist.", series: @serial}
        end
      end
    end

    def unwatch
      if token_user
        if token_user.watchlist.serials.include?(@serial)
          token_user.watchlist.serials.delete(@serial)
          render json: {success: "true", message: "Series has been removed from user's watchlist", series: @serial}
        else
          render json: {success: "false", message: "User doesn't have this series in watchlist", series: @serial}
        end
      end
    end

    def reviews
      respond_with @serial.reviews
    end

    def posts
      respond_with @serial.posts
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_serial
        @serial = Serial.find(params[:id])
      end

      def set_reviews
        @reviews = @serial.reviews
      end

      def set_posts
        @posts = @serial.posts
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def serial_params
        params.require(:serial).permit(:name, :date, :genre, :description)
      end
  end
end

app/controllers/serials_controller.rb
class SerialsController < ApplicationController
  include UserReviewsPosts

  skip_before_filter :user_admin, only: [:show, :index, :add, :remove,:watch, :unwatch, :show_reviews, :show_posts, :seen, :unseen]
  skip_before_filter :authorize, only: [:show, :index, :show_reviews, :show_posts]
  before_action :set_serial, except: [:index, :create, :new]
  before_action :set_reviews, only: [:show, :show_reviews]
  before_action :set_posts, only:[:show, :show_posts]

  # GET /serials
  # GET /serials.json
  def index
    @serials = Serial.all
  end

  # GET /serials/1
  # GET /serials/1.json
  def show
    if @serial.poster.nil?
    series_search = Serial.search_poster(@serial.name)
      unless(series_search[0].nil?)
        @poster = series_search[0]['images']['poster']
        @serial.poster = @poster
        @serial.save
      end
    end
  end

  # GET /serials/new
  def new
    @serial = Serial.new
  end

  # GET /serials/1/edit
  def edit
  end

  # POST /serials
  # POST /serials.json
  def create
    @serial = Serial.new(serial_params)

    respond_to do |format|
      if @serial.save
        format.html { redirect_to @serial, notice: 'Serial was successfully created.' }
        format.json { render action: 'show', status: :created, location: @serial }
      else
        format.html { render action: 'new' }
        format.json { render json: @serial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /serials/1
  # PATCH/PUT /serials/1.json
  def update
    respond_to do |format|
      if @serial.update(serial_params)
        format.html { redirect_to @serial, notice: 'Serial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @serial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /serials/1
  # DELETE /serials/1.json
  def destroy
    @serial.destroy
    respond_to do |format|
      format.html { redirect_to serials_url }
      format.json { head :no_content }
    end
  end

  def add
    if current_user
      if current_user.serials.include?(@serial)
        redirect_to @serial, notice: "You already follow this series"
      else
        current_user.serials << @serial
        respond_to do |format|
          format.html { redirect_to @serial, notice: "#{@serial.name} was successfully added!" }
          format.js { render 'layouts/update_action_menu' }
        end
      end
    end
  end

  def remove
    if current_user
      if current_user.serials.include?(@serial)
        current_user.serials.delete(@serial)
        respond_to do |format|
          format.html { redirect_to @serial, notice: "#{@serial.name} was successfully removed!" }
          format.js { render 'layouts/update_action_menu' }
        end
      else
        redirect_to @serial, notice: "You can't delete #{@serial.name}, D'OH!!!"
      end
    end
  end

  def watch
    if current_user
      if current_user.watchlist.serials.include?(@serial)
        redirect_to @serial, notice: "You already added this series to your watchlist"
      else
        current_user.watchlist.serials << @serial
        respond_to do |format|
          format.html { redirect_to @serial, notice: "#{@serial.name} was successfully added to watchlist!" }
          format.js { render 'layouts/update_action_menu' }
        end
      end
    end
  end

  def unwatch
    if current_user
      if current_user.watchlist.serials.include?(@serial)
        current_user.watchlist.serials.delete(@serial)
        respond_to do |format|
          format.html { redirect_to @serial, notice: "#{@serial.name} was successfully removed from watchlist!" }
          format.js { render 'layouts/update_action_menu' }
        end
      else
        redirect_to @serial, notice: "You can't delete #{@serial.name} from watchlist, D'OH!!!"
      end
    end
  end

  def seen
    if current_user
      @serial.seasons.map{|s| s.episodes}.flatten.each do |e|
        unless current_user.watched.episodes.include?(e)
          current_user.watched.episodes << e
        end
      end
      respond_to do |format|
          format.html { redirect_to serial_url(@serial), notice: "This whole series was marked as seen!" }
          format.js { render 'layouts/update_action_menu' }
      end
    end
  end

  def unseen
    if current_user
      @serial.seasons.map{|s| s.episodes}.flatten.each do |e|
        if current_user.watched.episodes.include?(e)
          current_user.watched.episodes.delete(e)
        end
      end
      respond_to do |format|
          format.html { redirect_to serial_url(@serial), notice: "This whole series was marked as seen!" }
          format.js { render 'layouts/update_action_menu' }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serial
      @serial = Serial.find(params[:id])
    end

    def set_reviews
      @reviews = @serial.reviews
    end

    def set_posts
      @posts = @serial.posts
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serial_params
      params.require(:serial).permit(:name, :date, :genre, :description)
    end
end

app/helpers/serials_helper.rb
module SerialsHelper
end

app/views/serials/_action_menu.html.erb
<ul>
	<li><%= add_remove_link(@serial) %></li>
	<li><%= watch_unwatch_link(@serial) %></li>
	<li><%= seen_unseen_serial_link(@serial) %></li>
</ul>

app/views/serials/_admin_bar.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
      <li><%= link_to 'Edit Serial', edit_serial_path(@serial) %></li>
      <li><%= link_to 'New Season', new_serial_season_path(@serial) %></li>
  </ul>
<% end %>

app/views/serials/_content.html.erb
<div class="show-header">
    <div class="show-header-title">
            <h1><%= @serial.name %></h1>
    </div>

    <p class="description"><%= simple_format(@serial.description) %></p>
</div>

app/views/serials/_form.html.erb
<%= form_for(@serial) do |f| %>
  <% if @serial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@serial.errors.count, "error") %> prohibited this serial from being saved:</h2>

      <ul>
      <% @serial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id:'name' %>
    <%=link_to 'Clik here to fill the fields', nil, class:'fill-serial-form'%>
  </div>

<div><%=link_to 'More info here', nil, id:'info', hidden: true %></div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date, start_year: 1900, end_year: Time.now.year+2, discard_hour: true %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre, id:'genre' %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, id:'description' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/serials/_sidebar.html.erb
<div class="show-action-menu">
		<%= render 'action_menu' %>
</div>

<img src="<%= @serial.poster%>">

<div class="show-detail-module show-details">
	<h3>Serial Details</h3>
	<ul>
		<li>Date: <%= @serial.date.to_date().to_s(:long) %></li>
		<li>Genre: <%= @serial.genre %></li>
	</ul>
</div>

<div class="show-detail-module show-seasons">
	<h3><%= link_to "Seasons »", serial_seasons_path(@serial) %></h3>
	<% if @serial.seasons.empty? %>
	<p>We're sorry, we don't have any season yet</p>
	<% else %>
		<ul>
			<% @serial.seasons.each do |s| %>
			<li><%= link_to "Season #{s.number}", serial_season_path(@serial,s) %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/serials/edit.html.erb
<h1>Editing serial</h1>

<%= render 'form' %>

<%= link_to 'Show', @serial %> |
<%= link_to 'Back', serials_path %>

app/views/serials/index.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
      <li><%= link_to 'New Serial', new_serial_path %></li>
  </ul>
<% end %>

<h1>Series</h1>

<div class="index_shows_panel">

    <% @serials.sort {|a,b| a.name <=> b.name }.each do |serial| %>


        <div class="index_shows_item">
           <%=link_to image_tag(serial.poster), serial_path(serial) %>
            <p><%= link_to "#{serial.name}", serial_path(serial) %></p>

        </div>

      
    <% end %>

</div>

app/views/serials/new.html.erb
<h1>New serial</h1>

<%= render 'form' %>

<%= link_to 'Back', serials_path %>

app/views/serials/show.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
      <li><%= link_to 'Edit Serial', edit_serial_path(@serial) %></li>
      <li><%= link_to 'New Season', new_serial_season_path(@serial) %></li>
  </ul>
<% end %>

<div class="show-sidebar">
	<div class="show-action-menu">
		<%= render 'action_menu' %>
	</div>

	<img src="http://placehold.it/216x319&text=<%= @serial.name%>">

	<div class="show-detail-module show-details">
		<h3>Serial Details</h3>
		<ul>
			<li>Date: <%= @serial.date.to_date().to_s(:long) %></li>
			<li>Genre: <%= @serial.genre %></li>
		</ul>
	</div>

	<div class="show-detail-module show-seasons">
		<h3><%= link_to "Seasons »", serial_seasons_path(@serial) %></h3>
		<% if @serial.seasons.empty? %>
		<p>We're sorry, we don't have any season yet</p>
		<% else %>
			<ul>
				<% @serial.seasons.each do |s| %>
				<li><%= link_to "Season #{s.number}", serial_season_path(@serial,s) %></li>
				<% end %>
			</ul>
		<% end %>
	</div>
</div>

<div class="show-content">
	<div class="show-header">
		<div class="show-header-title">
			<h1><%= @serial.name %></h1>
		</div>

		<p class="description"><%= @serial.description %></p>
	</div>

	<div class="show-users-content">
    	<%= render "layouts/user_content" %>
	</div>

</div>

app/views/serials/show_posts.html.erb
<%= render 'admin_bar' %>

<div class="show-sidebar">
	<%= render 'sidebar' %>
</div>

<div class="show-content">
	<%= render 'content' %>

	<div class="show-users-content">
    	<%= render "layouts/user_content_posts" %>
	</div>

</div>

app/views/serials/show_reviews.html.erb
<%= render 'admin_bar' %>

<div class="show-sidebar">
	<%= render 'sidebar' %>
</div>

<div class="show-content">
	<%= render 'content' %>

	<div class="show-users-content">
    	<%= render "layouts/user_content_reviews" %>
	</div>

</div>