config/routes.rb
S0::Application.routes.draw do

  resources :searches, path: "/search"

  concern :reviewable do 
    resources :reviews, only: [:create, :destroy, :update]
  end

  get "/movies/:id/reviews", to:"movies#show_reviews"
  get "/movies/:id/posts", to:"movies#show_posts"
  get "/series/:id/reviews", to:"serials#show_reviews"
  get "/series/:id/posts", to:"serials#show_posts"
  get "/series/:serial_id/seasons/:id/reviews", to: "seasons#show_reviews"
  get "/series/:serial_id/seasons/:id/posts", to: "seasons#show_posts"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/reviews", to:"episodes#show_reviews"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/posts", to:"episodes#show_posts"

  concern :commentable do 
    resources :posts, only: [:index, :create, :destroy, :update]
  end

  resources :movies, concerns: [:reviewable, :commentable]

  resources :serials, path: "/series", concerns: [:reviewable, :commentable] do
    resources :seasons, concerns: [:reviewable, :commentable] do
        resources :episodes, concerns: [:reviewable, :commentable]
    end
  end
  
  resources :sessions, only: [:create, :new, :destroy]
  get "/login", to: "sessions#create", as: :log_in
  get "/logout", to: "sessions#destroy", as: :log_out
  get "/signup", to: "users#new", as: :sign_up
  match "/login", to: "sessions#create", via: :post

  get "403", to: "pages#no_access", as: :access_denied

  get "/me", to: "users#me", as: :my_profile
  get "/me/shows", to:"followed_shows#shows", as: :my_shows
  get "/me/series", to:"followed_shows#serials", as: :my_serials
  get "/me/movies", to:"followed_shows#movies", as: :my_movies
  get "/me/watchlist", to:"watchlists#my_watchlist", as: :my_watchlist
  get "/me/tracking/serials/:id", to:"watched#tracking", as: :my_tracking
  get "/me/tracking/serials/:serial_id/seasons/:season_id", to:"watched#detail", as: :my_tracking_detail
  get "/me/seen", to:"watched#my_watched", as: :my_watched

  resources :users do
    resource :watchlists, path: "/watchlist"
  end
  resources :users do
    resource :watcheds, path: "/watched"
  end

  get "/series/:id/add", to:"serials#add", as: :add_serial
  get "/series/:id/remove", to:"serials#remove", as: :remove_serial
  get "/movies/:id/add", to:"movies#add", as: :add_movie
  get "/movies/:id/remove", to:"movies#remove", as: :remove_movie
  get "/series/:id/watch", to:"serials#watch", as: :watch_serial
  get "/series/:id/unwatch", to:"serials#unwatch", as: :unwatch_serial
  get "/series/:id/seen", to:"serials#seen", as: :seen_serial
  get "/series/:id/unseen", to:"serials#unseen", as: :unseen_serial
  get "/movies/:id/watch", to:"movies#watch", as: :watch_movie
  get "/movies/:id/unwatch", to:"movies#unwatch", as: :unwatch_movie
  get "/watchlist/:id/remove", to:"watchlist#remove", as: :remove_from_watchlist
  get "/movies/:id/seen", to:"movies#seen", as: :seen_movie
  get "/movies/:id/unseen", to:"movies#unseen", as: :unseen_movie
  get "/series/:serial_id/seasons/:id/seen", to:"seasons#seen", as: :seen_season
  get "/series/:serial_id/seasons/:id/unseen", to:"seasons#unseen", as: :unseen_season
  get "/series/:serial_id/seasons/:season_id/episodes/:id/seen", to:"episodes#seen", as: :seen_episode
  get "/series/:serial_id/seasons/:season_id/episodes/:id/unseen", to:"episodes#unseen", as: :unseen_episode

  get "/me/:id/watching", to:"watched#my_watched", as: :my_watching_series
  get "/me/:id/seen/series", to:"watched#series", as: :my_seen_series
  get "/me/:id/seen/movies", to:"watched#movies", as: :my_seen_movies

  match "/series/:serial_id/seasons/:season_id/episodes/:id/add_user_tags", to: "episodes#add_user_tags", via: :post
  get "/series/:serial_id/seasons/:season_id/episodes/:id/remove_user_tag/:tag_id", to: "episodes#remove_user_tag"

  root 'pages#index'

  namespace :api, defaults: {format: 'json'} do
    
    resources :movies do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'seen'
        get 'unseen'
        get 'reviews'
        get 'posts'
      end
    end

    resources :serials, path: "series" do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'reviews'
        get 'posts'
      end

      resources :seasons do
        member do
          get 'reviews'
          get 'posts'
        end

        resources :episodes do
          member do
            get 'seen'
            get 'unseen'
            get 'reviews'
            get 'posts'
          end
        end
      end
    end
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :show_users, dependent: :destroy
    has_many :shows, through: :show_users
    has_many :serials, through: :show_users
    has_many :movies, through: :show_users

    has_one :watchlist, dependent: :destroy
    has_one :watched, dependent: :destroy

    has_one :access_token
    
    before_create :build_default_watched
    before_create :build_default_watchlist
    # has_many :serials_users
    # has_many :serials, through: :serials_users
    # accepts_nested_attributes_for :serials_users, allow_destroy: true

    # has_many :movies_users
    # has_many :movies, through: :movies_users
    # accepts_nested_attributes_for :movies_users, allow_destroy: true

    has_secure_password

    validates :name, presence: true
    validates :username, presence: true, uniqueness: {case_sensitive: false}
    validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, uniqueness: true
    validates :role, inclusion: { in: %w{admin user} }


    def to_param
        username
    end

    def self.find(input)
        find_by(username: input)
    end

    def gravatar_url(size)
        gravatar_hash = Digest::MD5.hexdigest(email.downcase.strip)
        gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_hash}?s=#{size}&d=mm"
    end

    def get_access_token
        unless self.access_token
            self.access_token = AccessToken.create
        end
        self.access_token.token
    end


    def score_update(parent)
        self.score = self.watched.episodes.size*2 + self.watched.movies.size*2
        unless(parent.nil?)
            count= parent.posts.size + parent.reviews.size*5
            save_posts_reviews_count(count)
        end
        unless(@pr_count.nil?)
            self.score = self.score + @pr_count
        end
        self.save
        self.score
    end
   
    def save_posts_reviews_count count
        @pr_count = count
    end


    private

    def build_default_watchlist
        build_watchlist
    end

    def build_default_watched
        build_watched
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:show, :new, :create]
  skip_before_filter :user_admin, only: [:show, :edit, :update, :me]
  before_action :can_edit, only: [:edit, :update] 
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if user_admin?(current_user)
      @user.role = params[:user][:role]
    else
      @user.role = "user"
    end

    @user.score = 0

    respond_to do |format|
      if @user.save
         # Tell the UserMailer to send a welcome Email after save
        #UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
        if !user_admin?(current_user)
          session[:user_id] = @user.id
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if user_admin?(current_user)
      @user.role = params[:user][:role]
      @user.score = params[:user][:score]
    end

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def me
    redirect_to current_user
  end


  private
    def can_edit
      unless user_admin?(current_user) || current_user == User.find(params[:id])
        redirect_to access_denied_path, notice: "You can't edit other user's profile!" 
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def is_himself?(user)
      if current_user
        user == current_user
      end 
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, {required: ""} %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, {required: ""} %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, {type: "email", validate: "", required: ""} %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, {required: ""}%>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, {required: ""}%>
  </div>

  <% if user_admin?(current_user) %>
  <h3>Admin Options</h3>
  
  <div class="field">
    <%= f.label :role %>
    <%= select_tag "user[role]", options_for_select(["user","admin"], @user.role) %>
  </div>
  
  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>
  
  <% end%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit-user-picture">
  <% gravatar_hash = Digest::MD5.hexdigest(@user.email.downcase.strip)
   gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_hash}?s=180&d=mm" %>
     <%= tag(:img, src: gravatar_url, class: "edit-user-profile-pic") %>

    <p class="edit-user-picture-info">You can change your profile picture at <a href="http://gravatar.com" target="_blank">gravatar.com</a></p>

    <% if user_admin?(current_user) %>
      <h3>Admin Options</h3>
      
      <div class="field">
        <%= f.label :role %>
        <%= select_tag "user[role]", options_for_select(["user","admin"], @user.role) %>
      </div>
      
      <div class="field">
        <%= f.label :score %>
        <%= f.number_field :score %>
      </div>
    <% end%>
  </div>

  <div class="edit-user-fields">

  <h3>Information</h3>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, {required: ""} %>
    </div>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, {required: ""} %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, {validate: "", type: "email", required: ""}%>
    </div>

  <h3>Change Password</h3>
  <small> or leave both inputs blank</small>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="edit-user-shows">
    <!-- <h3>Shows</h3>


    <div class="field">
      Series Agregadas:
      <%Serial.all.each do |serial| %>
          <div>
            <%= check_box_tag  "user[serial_ids][]", serial.id, @user.serials.include?(serial) %>
            <%= label_tag  serial.name %>
          </div>
      <% end %>
    </div>
    <div class="field">
      Películas Agregadas:
      <%Movie.all.each do |movie| %>
          <div>
            <%= check_box_tag  "user[movie_ids][]", movie.id, @user.movies.include?(movie) %>
            <%= label_tag  movie.name %>
          </div>
      <% end %>
    </div>
  -->
  </div>
  <div class="actions">
    <%= f.submit "Update Profile" %> or <%= link_to 'Cancel', @user %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<div class="edit-user-form">
	<%= render 'form_edit' %>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Role</th>
      <th>Score</th>
      <th>Series Agregadas</th>
      <th>Películas Agregadas</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.score %></td>
        <td><%= user.serials.map{|s| link_to s.name, serial_path(s)}.join(", ").html_safe%></td>
        <td><%= user.movies.map{|m| link_to m.name, movie_path(m)}.join(" ,").html_safe %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for :top_user_bar do %>
	 <%= link_to "Already have an account? Log in!", log_in_path, id: "top-bar-login-button" %>
<% end %>

<h1>Sign up!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
    <li><%= link_to "Edit user", edit_user_path(@user) %></li>
  </ul>
<% end %>

<% gravatar_hash = Digest::MD5.hexdigest(@user.email.downcase.strip)
   gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_hash}?s=120&d=mm"
   user_access_token = @user.get_access_token
%>



<div id="user-profile-desc">
  <div id="user-profile-picture">
    <%= tag(:img, src: gravatar_url) %>
  </div>
  <div id="user-profile-data">
    <h1 id="user-profile-title"><%= @user.name %></h1>
    <ul> 
      <li>Username: <strong><%= @user.username %></strong></li>
      <li>Score: <strong><%= (@user.score != 0)? @user.score : 0; %></strong></li>
      <% if is_himself?(@user) || user_admin?(current_user) %>
      <li><small>Access Token: <%= user_access_token %></small></li>
      <% end %>
    </ul>
  </div>

  <% if is_himself?(@user) %>
    <div id="user-profile-buttons">
      <%= link_to 'Edit your profile', edit_user_path(@user) %>
    </div>
  <% end  %>
</div>

<h2>Series</h2>
  <% if @user.serials.any? %>
    <ul>
    <% @user.serials.each do |s|  %>
      <li><%= link_to s.name, serial_path(s) %></li>
    <%end%>
    </ul>
  <% else %>
    <p class="center-warning"><%= if is_himself?(@user); "Woah, you don't have any series added, why not #{link_to 'browsing', serials_path }?".html_safe else "#{@user.username} hasn't added any series yet." end%></p>
  <% end %>

<h2>Movies</h2>
<% if @user.movies.any? %>
  <ul>
  <% @user.movies.each do |m|  %>
    <li><%= link_to m.name, movie_path(m) %></li>
  <%end%>
  </ul>
<% else %>
    <p class="center-warning"><%= if is_himself?(@user); "Woah, you don't have any movies added, why not #{link_to 'browsing', movies_path }?".html_safe else "#{@user.username} hasn't added any movies yet." end%></p>
<% end %>