config/routes.rb
S0::Application.routes.draw do

  resources :searches, path: "/search"

  concern :reviewable do 
    resources :reviews, only: [:create, :destroy, :update]
  end

  get "/movies/:id/reviews", to:"movies#show_reviews"
  get "/movies/:id/posts", to:"movies#show_posts"
  get "/series/:id/reviews", to:"serials#show_reviews"
  get "/series/:id/posts", to:"serials#show_posts"
  get "/series/:serial_id/seasons/:id/reviews", to: "seasons#show_reviews"
  get "/series/:serial_id/seasons/:id/posts", to: "seasons#show_posts"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/reviews", to:"episodes#show_reviews"
  get "/series/:serial_id/seasons/:season_id/episodes/:id/posts", to:"episodes#show_posts"

  concern :commentable do 
    resources :posts, only: [:index, :create, :destroy, :update]
  end

  resources :movies, concerns: [:reviewable, :commentable]

  resources :serials, path: "/series", concerns: [:reviewable, :commentable] do
    resources :seasons, concerns: [:reviewable, :commentable] do
        resources :episodes, concerns: [:reviewable, :commentable]
    end
  end
  
  resources :sessions, only: [:create, :new, :destroy]
  get "/login", to: "sessions#create", as: :log_in
  get "/logout", to: "sessions#destroy", as: :log_out
  get "/signup", to: "users#new", as: :sign_up
  match "/login", to: "sessions#create", via: :post

  get "403", to: "pages#no_access", as: :access_denied

  get "/me", to: "users#me", as: :my_profile
  get "/me/shows", to:"followed_shows#shows", as: :my_shows
  get "/me/series", to:"followed_shows#serials", as: :my_serials
  get "/me/movies", to:"followed_shows#movies", as: :my_movies
  get "/me/watchlist", to:"watchlists#my_watchlist", as: :my_watchlist
  get "/me/tracking/serials/:id", to:"watched#tracking", as: :my_tracking
  get "/me/tracking/serials/:serial_id/seasons/:season_id", to:"watched#detail", as: :my_tracking_detail
  get "/me/seen", to:"watched#my_watched", as: :my_watched

  resources :users do
    resource :watchlists, path: "/watchlist"
  end
  resources :users do
    resource :watcheds, path: "/watched"
  end

  get "/series/:id/add", to:"serials#add", as: :add_serial
  get "/series/:id/remove", to:"serials#remove", as: :remove_serial
  get "/movies/:id/add", to:"movies#add", as: :add_movie
  get "/movies/:id/remove", to:"movies#remove", as: :remove_movie
  get "/series/:id/watch", to:"serials#watch", as: :watch_serial
  get "/series/:id/unwatch", to:"serials#unwatch", as: :unwatch_serial
  get "/series/:id/seen", to:"serials#seen", as: :seen_serial
  get "/series/:id/unseen", to:"serials#unseen", as: :unseen_serial
  get "/movies/:id/watch", to:"movies#watch", as: :watch_movie
  get "/movies/:id/unwatch", to:"movies#unwatch", as: :unwatch_movie
  get "/watchlist/:id/remove", to:"watchlist#remove", as: :remove_from_watchlist
  get "/movies/:id/seen", to:"movies#seen", as: :seen_movie
  get "/movies/:id/unseen", to:"movies#unseen", as: :unseen_movie
  get "/series/:serial_id/seasons/:id/seen", to:"seasons#seen", as: :seen_season
  get "/series/:serial_id/seasons/:id/unseen", to:"seasons#unseen", as: :unseen_season
  get "/series/:serial_id/seasons/:season_id/episodes/:id/seen", to:"episodes#seen", as: :seen_episode
  get "/series/:serial_id/seasons/:season_id/episodes/:id/unseen", to:"episodes#unseen", as: :unseen_episode

  get "/me/:id/watching", to:"watched#my_watched", as: :my_watching_series
  get "/me/:id/seen/series", to:"watched#series", as: :my_seen_series
  get "/me/:id/seen/movies", to:"watched#movies", as: :my_seen_movies

  match "/series/:serial_id/seasons/:season_id/episodes/:id/add_user_tags", to: "episodes#add_user_tags", via: :post
  get "/series/:serial_id/seasons/:season_id/episodes/:id/remove_user_tag/:tag_id", to: "episodes#remove_user_tag"

  root 'pages#index'

  namespace :api, defaults: {format: 'json'} do
    
    resources :movies do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'seen'
        get 'unseen'
        get 'reviews'
        get 'posts'
      end
    end

    resources :serials, path: "series" do
      member do
        get 'add'
        get 'remove'
        get 'watch'
        get 'unwatch'
        get 'reviews'
        get 'posts'
      end

      resources :seasons do
        member do
          get 'reviews'
          get 'posts'
        end

        resources :episodes do
          member do
            get 'seen'
            get 'unseen'
            get 'reviews'
            get 'posts'
          end
        end
      end
    end
  end

  

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  include UserContentable

  belongs_to :season

  has_many :episode_taggings, dependent: :destroy
  has_many :tags, through: :episode_taggings

  has_many :user_episode_taggings
  has_many :user_tags, through: :user_episode_taggings, source: :tag

  validates :number, uniqueness: {scope: :season_id}, presence: true
  validates :name, presence: true, uniqueness: {scope: :season_id,case_sensitive: false}

  def to_param
	  number
  end

  def self.find(input)
  	find_by(number: input)
  end

  def self.tagged_with(name)
    Tag.find_by_name(name).episodes
  end

  def tags_list
    tags.map(&:name).join(", ")
  end

  def user_tags_list(user)
    out_tags_list = []
    UserEpisodeTagging.where(episode_id: id, user: user).map(&:tag_id).each do |o|
      out_tags_list << Tag.find(o)
    end
    out_tags_list.map(&:name).join(", ")
  end

  def user_user_tags(user)
    out_tags_list = []
    UserEpisodeTagging.where(episode_id: id, user: user).map(&:tag_id).each do |o|
      out_tags_list << Tag.find(o)
    end
    out_tags_list
  end
  def all_user_tags_list
    user_tags
  end
  
  def update_user_tags(update_tags,episode,user)
    param_tags =[]
    update_tags.split(",").uniq.map do |n|
      param_tags << Tag.find_or_create_by(name: n.strip.downcase)
    end
    new_tags = param_tags - user_tags
    new_tags.each do |tag|
      UserEpisodeTagging.create(episode: episode, tag: tag, user: user)
    end
 
  end

  def delete_user_tag(tag_name,episode,user)
    tag = Tag.find_by(name: tag_name.strip.downcase)
    remove_record = UserEpisodeTagging.where(episode: episode, tag:tag, user: user)
    remove_record.each do |o|
      o.destroy
    end
  end

  def update_tags(update_tags,episode)
    if update_tags
      param_tags =[]
      update_tags.split(",").uniq.map do |n|
        param_tags << Tag.find_or_create_by(name: n.strip.downcase)
      end
      new_tags = param_tags - tags
      remove_tags = tags - param_tags
      new_tags.each do |tag|
        EpisodeTagging.create(episode: episode, tag: tag)
      end
      remove_tags.each do |tag|
        remove_record = EpisodeTagging.where(episode: episode, tag:tag)
        remove_record.each do |o|
          o.destroy
        end
      end
    end
  end

end

app/controllers/api/episodes_controller.rb
module Api
  class EpisodesController < ApiApplicationController

    before_filter :token_admin, only: [:create, :update, :destroy]
    before_filter :token_user, only: [:seen, :unseen]
    
    before_action :set_season_serial, except: [:create]
    before_action :set_episode, except: [:index, :create, :new]
    before_action :set_reviews, only:[:show, :reviews]
    before_action :set_posts, only:[:show, :posts]

    # GET /episodes
    # GET /episodes.json
    def index
      render json: {episodes: @season.episodes, season: @season}
    end

    # GET /episodes/1
    # GET /episodes/1.json
    def show
      render json: {episode: @episode, season: @season}
    end

    # POST /episodes
    # POST /episodes.json
    def create
      @serial = Serial.find_by(id: params[:serial_id])
      @season = @serial.seasons.find_by(number: params[:season_id])
      @episode = Episode.create(episode_params)
      @episode.season_id = @season.id
      @season.episodes << @episode
      if @episode.id
        render json: {success: "true", message: "Episode has been created", episode: @episode, season: @season}
      else
        render json: {success: "false", message: "Episode couldn't be created", episode: @episode, season: @season, serial: @serial}
      end
    end

    # PATCH/PUT /episodes/1
    # PATCH/PUT /episodes/1.json
    def update
      @episode.update(episode_params)
      render json: {success: "true", message: "Episode has been upadated"}
    end

    # DELETE /episodes/1
    # DELETE /episodes/1.json
    def destroy
      if @episode
        @episode.destroy
        render json: {success: "true", message: "Episode has been deleted."}
      else
        render json: {success: "false", message: "Episode couldn't be deleted."}
      end
    end


    def seen
      if token_user
        if token_user.watched.episodes.include?(@episode)
          render json: {success: "false", message: "User has already seen episode", episode: @episode}
        else
          token_user.watched.episodes << @episode
          token_user.score_update(nil)
          render json: {success: "true", message: "Episode has been marked as seen", episode: @episode}
        end
      end
    end

    def unseen
      if token_user
        if token_user.watched.episodes.include?(@episode)
          token_user.watched.episodes.delete(@episode)
          token_user.score_update(nil)
          render json: {success: "true", message: "Episode has been marked as unseen", episode: @episode}
        else
          render json: {success: "false", message: "User has not seen this episode.", episode: @episode}
        end
      end
    end

    def reviews
      respond_with @episode.reviews
    end

    def posts
      respond_with @episode.posts
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_episode
        @episode = @season.episodes.find_by(number: params[:id])
      end

      def set_season_serial
        @serial = Serial.find(params[:serial_id])
        @season = @serial.seasons.find_by(number: params[:season_id])
      end

      def set_reviews
        @reviews = @episode.reviews
      end

      def set_posts
        @posts = @episode.posts
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def episode_params
        params.require(:episode).permit(:name, :description, :date, :number, :write, :director, :duration, :season_id, :tag_list)
      end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  include UserReviewsPosts

  skip_before_filter :user_admin, only: [:show, :index, :add_user_tags, :remove_user_tag, :seen, :unseen, :show_reviews, :show_posts]
  skip_before_filter :authorize, only: [:show, :index, :show_reviews, :show_posts]
  before_action :set_season_serial
  before_action :set_episode, except: [:index, :create, :new]
  before_action :set_reviews, only:[:show, :show_reviews]
  before_action :set_posts, only:[:show, :show_posts]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = @season.episodes
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    param_tags = params[:episode][:tags_list]
    params[:episode].delete(:tags_list)
    @episode = Episode.new(episode_params)
    @episode.season_id = @season.id
    @episode.update_tags(param_tags, @episode)



    respond_to do |format|
      if @episode.save
        series = Serial.find_by_id(@season.serial_id)
        User.all.each do |u|
        if u.serials.include?(series)
          #UserMailer.new_episode(u).deliver
        end
        end
        format.html { redirect_to [@serial,@season,@episode], notice: 'Episode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @episode }
      else
        format.html { render action: 'new' }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    param_tags = params[:episode][:tags_list]
    params[:episode].delete(:tags_list)
    @episode.update_tags(param_tags, @episode)
        
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to [@serial,@season,@episode], notice: 'Episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to serial_season_episodes_url }
      format.json { head :no_content }
    end
  end


  def seen
    if current_user
      if current_user.watched.episodes.include?(@episode)
        redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "You already marked this episode as seen!"
      else
        current_user.watched.episodes << @episode
        current_user.score_update(nil)
        respond_to do |format|
          format.html { redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "#{@episode.name} was successfully marked as seen! :D" }
          format.js { render 'layouts/update_action_menu' }
        end
      end
    end
  end

  def unseen
    if current_user
      if current_user.watched.episodes.include?(@episode)
        current_user.watched.episodes.delete(@episode)
        current_user.score_update(nil)
        respond_to do |format|
          format.html { redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "#{@episode.name} was successfully marked as unseen!" }
          format.js { render 'layouts/update_action_menu' }
        end        
      else
        redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "You can't unseen #{@episode.name}, cause you have not seen it!"
      end
    end
  end

  def add_user_tags
    if current_user
      @episode.update_user_tags(params[:user_tags_list], @episode, current_user)
      redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "Your tags were added!"
    else 
      redirect_to access_denied_path
    end
  end

  def remove_user_tag
    if current_user
      if @episode.user_user_tags(current_user).include?(Tag.find_by(name: params[:tag_id]))
        @episode.delete_user_tag(params[:tag_id],@episode,current_user)
        redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "Your tag \"#{params[:tag_id]}\" has been removed"
      else
        redirect_to serial_season_episode_url(@serial,@season,@episode), notice: "Whoah, trying to get rid of something you don't have? Nope"
      end
    else 
      redirect_to access_denied_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = @season.episodes.find_by(number: params[:id])
    end

    def set_season_serial
      @serial = Serial.find(params[:serial_id])
      @season = @serial.seasons.find_by(number: params[:season_id])
    end

    def set_reviews
      @reviews = @episode.reviews
    end

    def set_posts
      @posts = @episode.posts
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :description, :date, :number, :write, :director, :duration, :season_id, :tag_list)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_action_menu.html.erb
<ul>
  <li><%= seen_unseen_episode_link(@episode) %></li>
</ul>

app/views/episodes/_admin_bar.html.erb
<% content_for :admin_bar_panel do %>
    <ul>
        <li><%= link_to 'Edit Episode', edit_serial_season_episode_path(@serial,@season,@episode) %></li>
    </ul>
<% end %>

app/views/episodes/_content.html.erb
<div class="show-header">
	<div class="show-header-title">
  		<p class="bread-crumb"><%= link_to @serial.name, serial_path(@serial) %> - <%= link_to "Season #{@season.number}",serial_season_path(@serial,@season) %></p>
    	<h1><%= "S"+( "%02d" % @season.number)+"E"+("%02d") % @episode.number%> - <%= @episode.name %></h1>
    <%= link_to "View all episodes", serial_season_episodes_path(@serial,@season), class: "all-episodes-link" %>
	</div>

	<p class="description"><%= simple_format @episode.description %></p>
</div>

app/views/episodes/_form.html.erb
<%= form_for([@serial,@season,@episode]) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, start_year: 1900, end_year: Time.now.year+2, discard_hour: true %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :writer %><br>
    <%= f.text_field :write %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :tags_list, "Tag list (separated by comma)" %><br>
    <%= f.text_field :tags_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/_sidebar.html.erb
<div class="show-action-menu">
  <%= render 'action_menu' %>
</div>


<img src="<%= @serial.poster %>" />

<div class="show-detail-module show-details">
  <h3>Episode Details</h3>

  <ul>
      <li>Date: <%= @episode.date.to_date().to_s(:long) %></li>
      <li>Writer: <%= @episode.write %></li>
      <li>Director: <%= @episode.director %></li>
      <li>Duration: <%= @episode.duration %> min.</li>
  </ul>

</div>

<% if current_user %>
<div class="show-detail-module show-tags">
  <h3>Your Tags</h3>

  <%= render 'tag_form' %>

  <% if @episode.user_user_tags(current_user).any? %>
      <%= render 'user_tag_list' %>
  <% else %>
      <p> This episode hasn't been tagged </p>
  <% end %>
</div>
<% end %>

<div class="show-detail-module show-tags">
  <h3>Tags</h3>
  <%= if @episode.tags.any? 
      tag_ul_list(@episode.tags_list) 
    else 
      content_tag(:p, "This episode hasn't been tagged")
      end%>
</div>

app/views/episodes/_tag_form.html.erb
<%= form_tag serial_season_episode_path(@serial,@season,@episode)+"/add_user_tags" do %>
    <%= text_field_tag :user_tags_list, "", placeholder: "use, comma, as, separator", required: "" %>

<% end %>

app/views/episodes/_user_tag_list.html.erb
<ul>
<% @episode.user_tags_list(current_user).split(",").each do |tag| %>
	<li><%= tag.strip %> <span><%= link_to "remove", serial_season_episode_path(@serial,@season,@episode)+"/remove_user_tag/"+tag.strip%></span></li>
<%end%>
</ul>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', serial_season_episode_path(@serial,@season,@episode) %> |
<%= link_to 'Back', serial_season_episodes_path(@serial,@season) %>

app/views/episodes/index.html.erb
<% content_for :admin_bar_panel do %>
  <ul>
    <li><%= link_to 'Edit Season', edit_serial_season_path(@serial,@season) %></li>
    <li><%= link_to 'New Episode', new_serial_season_episode_path(@serial,@season) %></li>
  </ul>
<% end %>

<div class="show-sidebar">
  <div class="show-action-menu">
  </div>

   <%=image_tag("#{@serial.poster}")%>

  <div class="show-detail-module show-details">
    <h3>Season Details</h3>
    <ul>
      <li>Date: <%= @serial.date.to_date().to_s(:long) %></li>
    </ul>
  </div>


</div>

<div class="show-content">
  <div class="show-header">
    <div class="show-header-title">
      <p class="bread-crumb"><%= link_to @serial.name, serial_path(@serial) %></p>
      <h1><%= link_to "Season #{@season.number.to_s}", serial_season_path(@serial,@season) %>  - Episodes</h1>
      <%= link_to "View all seasons", serial_seasons_path(@serial), class: "all-seasons-link" %>
    </div>
  </div>

  <div class="show-list show-episode-list">
    <% if @season.episodes.empty? %>
      <p class="center-warning">Oops, we didn't find any episodes!</p>
    <% else %>
      <% @season.episodes.sort_by{|e| e.number}.each do |episode| %>
        <div class="show-episode-list-item">
          <div class="title">
            <h2><%= link_to "S"+( "%02d" % @season.number)+"E"+("%02d" % episode.number)+": "+episode.name, serial_season_episode_path(@serial,@season,episode) %></h2>
          </div>
          <p class="description"><%= episode.description %></p>

          <div class="episode-details">
            <ul>
              <li>Date: <%= episode.date.to_date().to_s(:long) %></li>
              <li>| Duration: <%= episode.duration %> min.</li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', serial_season_episodes_path(@serial,@season) %>

app/views/episodes/show.html.erb
<% content_for :admin_bar_panel do %>
    <ul>
        <li><%= link_to 'Edit Episode', edit_serial_season_episode_path(@serial,@season,@episode) %></li>
    </ul>
<% end %>

<div class="show-sidebar">
  <div class="show-action-menu">
    <ul>
          <li><%= seen_unseen_episode_link(@episode) %></li>
      </ul>
  </div>

  <img src="http://placehold.it/216x319&text=<%= @serial.name+ '- Season: '+@season.number.to_s+'- Episode: '+@episode.number.to_s %>" />

  <div class="show-detail-module show-details">
    <h3>Episode Details</h3>

    <ul>
        <li>Date: <%= @episode.date.to_date().to_s(:long) %></li>
        <li>Writer: <%= @episode.write %></li>
        <li>Director: <%= @episode.director %></li>
        <li>Duration: <%= @episode.duration %> min.</li>
    </ul>

  </div>

  <% if current_user %>
  <div class="show-detail-module show-tags">
    <h3>Your Tags</h3>

    <%= render 'tag_form' %>

    <% if @episode.user_user_tags(current_user).any? %>
        <%= render 'user_tag_list' %>
    <% else %>
        <p> This episode hasn't been tagged </p>
    <% end %>
  </div>
  <% end %>

  <div class="show-detail-module show-tags">
    <h3>Tags</h3>
    <%= if @episode.tags.any? 
        tag_ul_list(@episode.tags_list) 
      else 
        content_tag(:p, "This episode hasn't been tagged")
        end%>
  </div>

</div>

<div class="show-content">
  <div class="show-header">
    <div class="show-header-title">
      <p class="bread-crumb"><%= link_to @serial.name, serial_path(@serial) %> - <%= link_to "Season #{@season.number}",serial_season_path(@serial,@season) %></p>
        <h1><%= "S"+( "%02d" % @season.number)+"E"+("%02d") % @episode.number%> - <%= @episode.name %></h1>
        <%= link_to "View all episodes", serial_season_episodes_path(@serial,@season), class: "all-episodes-link" %>
    </div>

    <p class="description"><%= @episode.description %></p>
  </div>

  <div class="show-users-content">
    <%= render "layouts/user_content" %>
  </div>
</div>

app/views/episodes/show_posts.html.erb
<%= render 'admin_bar' %>

<div class="show-sidebar">
  <%= render 'sidebar' %>
</div>

<div class="show-content">
  <%= render 'content' %>

  <div class="show-users-content">
    <%= render "layouts/user_content_posts" %>
  </div>
</div>

app/views/episodes/show_reviews.html.erb
<%= render 'admin_bar' %>

<div class="show-sidebar">
  <%= render 'sidebar' %>
</div>

<div class="show-content">
  <%= render 'content' %>

  <div class="show-users-content">
    <%= render "layouts/user_content_reviews" %>
  </div>
</div>